name: Build Kivy App
on: [push, pull_request]

jobs:
  build-android:
    name: Android Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kivy/buildozer:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build with Buildozer
        run: buildozer -v android debug

      - name: Upload APK
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: |
            bin/*.apk
            .buildozer/android/platform/build-*/dists/*/build/outputs/**/*.apk

      - name: Upload Build Logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            .buildozer/**/*.log
            *.log
